# Generated by Django 3.0.5 on 2020-05-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('incident_description', models.TextField()),
                ('incident_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.IncidentLocation')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.IncidentType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.Profile')),
            ],
        ),
    ]
