# Generated by Django 3.0.5 on 2020-05-10 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date_time',
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 18, 6, 34, 985733)),
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.TimeField(default=datetime.time(18, 6, 34, 985733)),
        ),
    ]
