# Generated by Django 3.0.5 on 2020-05-10 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_auto_20200510_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 18, 55, 3, 543472)),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
