# Generated by Django 3.0.5 on 2020-05-12 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_auto_20200510_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
        migrations.AddField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 12, 38, 36, 454532, tzinfo=utc)),
        ),
    ]
