# Generated by Django 3.0.5 on 2020-05-12 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_auto_20200512_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date_time',
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 13, 42, 2, 302319)),
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
