# Generated by Django 3.0.5 on 2020-05-12 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_auto_20200512_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 13, 44, 31, 682454)),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.CharField(default=datetime.time(13, 44, 31, 682454), max_length=5),
        ),
    ]
