# Generated by Django 3.0.5 on 2020-05-12 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0007_auto_20200512_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 13, 48, 43, 327556)),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.CharField(default='12:48', max_length=5),
        ),
    ]
