# Generated by Django 3.0.5 on 2020-05-12 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0008_auto_20200512_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 13, 49, 37, 700692)),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default='12:49', max_length=5),
        ),
    ]
