# Generated by Django 3.0.5 on 2020-05-14 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0010_auto_20200512_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default='13:28', max_length=5),
        ),
    ]
