# Generated by Django 3.0.5 on 2020-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0011_auto_20200514_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default='13:29'),
        ),
    ]
