# Generated by Django 3.0.5 on 2020-05-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0012_auto_20200514_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default='23:41'),
        ),
    ]
