# Generated by Django 3.0.5 on 2020-05-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0013_auto_20200515_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default='23:47'),
        ),
    ]
