# Generated by Django 3.0.5 on 2020-05-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0014_auto_20200515_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default='00:07'),
        ),
    ]
